name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello! Thank you for opening your first issue in our repository. We will get back to you as soon as possible.'
          pr-message: 'Hello! Thank you for your first Pull Request (PR). Your contributions are very valuable to us, and a code review will be done shortly.'
